### PR TITLE
Distinguish host attributes from listeners.

### LINKED ISSUE #20: Default host attributes that are listeners get transformed incorrectly
0.5 code:

    <polymer-element name="chromedash-featurelist" on-scroll="{{onScrollList}}" on-keyup="{{onKeyUp}}">

gets transformed into:

    hostAttributes: {
        on-scroll: '{{onScrollList}}',
        on-keyup: '{{onKeyUp}}',
      },

This should instead be under `listeners` and from `{{}}`.

### PR DESCRIPTION
**Pull request by rictic**
Migrate listeners out of on-\* attributes on <polymer-element>.

Fixes #20.

### CODE REVIEW

File: lib/upgrade_html.js [hunk 1]
```diff
@@ -109,14 +110,25 @@ class Page {
...
       for (var attr in polyElem.attribs) {
         if (_.contains(knownAttributes, attr)) {
           continue;
         }
-        elementMetadata.hostAttrs[attr] = polyElem.attribs[attr];
+        var match = attr.match(/^on-(.*)$/);
+        if (match) {
+          var eventName = match[1];
+          var listenerFuncExpr = polyElem.attribs[attr];
+          match = listenerFuncExpr.match(/^\{\{(.*)\}\}$/);
```
Comment (azakus) [inline lib/upgrade_html.js]: This might technically be a `[[ ]]` expression, but that is not super likely.

File: lib/upgrade_js.js [hunk 2]
```diff
@@ -123,8 +125,8 @@ class Script {
 
     // hostAttributes
     var hostAttrsProperties = [];
-    for (var key in hostAttrs) {
-      var astVal = {type: 'Literal', value: hostAttrs[key]};
+    for (let key in hostAttrs) {
```
Comment (azakus) [inline lib/upgrade_js.js]: `let key of hostAttrs`

File: lib/upgrade_js.js [hunk 3]
```diff
@@ -145,6 +147,25 @@ class Script {
       });
     }
 
+    var listenerProperties = [];
+    for (let key in listeners) {
```
Comment (azakus) [inline lib/upgrade_js.js]: `of`

**Comment by azakus** [comment]
LGTM with nits

File: lib/upgrade_js.js (hunk 2 above)
Comment (rictic) [inline lib/upgrade_js.js]: hostAttrs isn't an iterator though. I get the error `undefined is not a function` with this, I believe because it's looking up Symbol('@@iterator') on hostAttrs.

File: lib/upgrade_js.js (hunk 3 above)
Comment (rictic) [inline lib/upgrade_js.js]: Ditto

File: lib/upgrade_html.js (hunk 1 above)
Comment (rictic) [inline lib/upgrade_html.js]: Good point, done.

**Comment by rictic** [comment]
Thanks for the review!

File: lib/upgrade_js.js (hunk 2 above)
Comment (azakus) [inline lib/upgrade_js.js]: Interesting. I thought objects and arrays got implicit iterators.
